# Generated by Django 3.1.7 on 2021-03-12 09:04

from django.db import migrations, models
import message.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to=message.models.product_photos_dir),
        ),
    ]
