# Generated by Django 3.1.7 on 2021-03-06 18:02

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to=product.models.product_photos_dir),
        ),
    ]
