# Generated by Django 3.1.7 on 2021-03-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210307_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available', to='product.product'),
        ),
    ]
