# Generated by Django 3.1.7 on 2021-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_pharmacy_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='countproduct',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
