# Generated by Django 3.1.7 on 2021-03-13 13:47

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='photo',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to=product.models.pharmacy_photos_dir),
        ),
    ]
