# Generated by Django 3.1.7 on 2021-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_reviewproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='product.product'),
        ),
    ]
